### ISSUE TITLE
Error 404 server 

### ISSUE THREAD

**Issue by DGrv** [mibe/Srtm2Osm#5]
Hi,

I was wondering if this is normal ? Is the server down sometimes or they change seomthing on their side ?
Is your wonderful tool still usable ?

````shell
C:\Users\***\Downloads\Software\Srtm2Osm > Srtm2Osm.exe -bounds2 47.6628 10.3707 50 -step 5 -o output.osm
Srtm2Osm v1.13.1.0 by Igor Brejc and others

Uses SRTM data to generate elevation contour lines for use in OpenStreetMap

Downloading data for SRTM index generation

An error occurred while accessing the network:
The remote server returned an error: (404) Not Found. (ProtocolError)
URI: https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Australia/
```

Thanks for your feedback.

**Comment by venon1983** [comment]
Hello, I have same problem.

**Comment by mibe** [comment]
The U.S. Geological Survey stopped publishing the SRTM data files. I found a copy of the files on this server: https://terrain.ardupilot.org/data/SRTM/
Give it a try with this patched build:
[Srtm2Osm-1.13.4112.0.zip](https://github.com/mibe/Srtm2Osm/files/6300026/Srtm2Osm-1.13.4112.0.zip)

I'd probably host the files on my server, if the license situation of these files is clear and make this possible...

**Comment by DGrv** [comment]
Thanks to have had a look.

I have a problem, but it may be my fault:

`Srtm2Osm.exe -bounds2 47.6628 10.3707 50 -step 5 -source "https://terrain.ardupilot.org/data/SRTM" -o output.osm`
or
`Srtm2Osm.exe -bounds2 47.6628 10.3707 50 -step 5 -o output.osm`


```Srtm2Osm v1.13.4112.0 by Igor Brejc and others

Uses SRTM data to generate elevation contour lines for use in OpenStreetMap

Calculating contour data for bound 10.203497521711,47.5501903704538,10.537902478289,47.7754096295461...
Downloading SRTM cell N47E010.hgt

ERROR: 1 is not a supported code page.
Parameter name: codepage
```

Do I miss something ?

**Comment by mibe** [comment]
No, that should have worked, it actually [works for me ™️](https://gist.github.com/mibe/4c39fe1726f4c2d559d8fdf9450b6655)
Weird...
[output.zip](https://github.com/mibe/Srtm2Osm/files/6306873/output.zip)

Could you please provide some info on your Operating System? Let me guess, it's Windows 10?

**Comment by DGrv** [comment]
Hi,

Yes you are right.
```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
System Locale:             en-us;English (United States)
Input Locale:              de;German (Germany)
```

Meaning for numbers:

![2021-04-14 16-52-30](https://user-images.githubusercontent.com/15691063/114731257-e0824180-9d41-11eb-8bba-edf7b5b43d15.jpg)

Thanks :)
