### ISSUE TITLE
Downloading fails with ERROR: 1 is not a supported code page

### ISSUE THREAD

**Issue by mibe** [mibe/Srtm2Osm#6]
Thanks to have had a look.

I have a problem, but it may be my fault:

`Srtm2Osm.exe -bounds2 47.6628 10.3707 50 -step 5 -source "https://terrain.ardupilot.org/data/SRTM" -o output.osm`
or
`Srtm2Osm.exe -bounds2 47.6628 10.3707 50 -step 5 -o output.osm`

```Srtm2Osm v1.13.4112.0 by Igor Brejc and others

Uses SRTM data to generate elevation contour lines for use in OpenStreetMap

Calculating contour data for bound 10.203497521711,47.5501903704538,10.537902478289,47.7754096295461...
Downloading SRTM cell N47E010.hgt

ERROR: 1 is not a supported code page.
Parameter name: codepage
```

Do I miss something ?

_Originally posted by @DGrv in https://github.com/mibe/Srtm2Osm/issues/5#issuecomment-818525547_

**Comment by mibe** [comment]
Hi,

Yes you are right.
```
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
System Locale:             en-us;English (United States)
Input Locale:              de;German (Germany)
```

Meaning for numbers:

![2021-04-14 16-52-30](https://user-images.githubusercontent.com/15691063/114731257-e0824180-9d41-11eb-8bba-edf7b5b43d15.jpg)

Thanks :)

_Originally posted by @DGrv in https://github.com/mibe/Srtm2Osm/issues/5#issuecomment-819581086_

**Comment by mibe** [comment]
@DGrv
This is actually an issue with SharpZipLib: icsharpcode/SharpZipLib#195.
Let's see if [this workaround here](https://stackoverflow.com/questions/46950386/sharpziplib-1-is-not-a-supported-code-page) fixes it...

**Comment by mibe** [comment]
Alright, if you want to give it a try, here's a pre-release build with that patch applied:
[Srtm2Osm-1.13.4205.0.zip](https://github.com/mibe/Srtm2Osm/files/6430395/Srtm2Osm-1.13.4205.0.zip)

**Comment by DGrv** [comment]
Hi Mibe,

Sorry for the delay. I did not look in detail the issue with the SharpZipLib.
Your pre-released build is working like a charm 👍 
Thanks a lot.
